### ISSUE TITLE
Impersonate not working while mfazones-app is enabled

### ISSUE THREAD

**Issue by ollimaz** [SUNET/nextcloud-mfazones#15]
The Impersonate app (https://apps.nextcloud.com/apps/impersonate) isn't working while the mfazones-app is active. Could you please investigate this.

**Comment by mickenordin** [comment]
Can you pleas try with 0.0.5 that was released today, and supply me with information about what version of nextcloud your are running, and what version of impersonate and also server logs that shows what might be going on?

**Comment by mickenordin** [comment]
Closing this because of lack of info. Please feel free to reopen if you want to supply more information.
