### ISSUE TITLE
Usability - after enabling MFA Zones, Folder is protected but no request is triggert - what is the multi factor?

### ISSUE THREAD

**Issue by apg1980** [SUNET/nextcloud-mfazones#17]
Hello,

i am using the latest NC28 an have enabled MFA Zones like descrived.
I've enabled an Folder for MFA Zones, this is getting protected and is now not getting opened.
Where is the Second Factor configured, what is used for?
This is not descrived in the documentation.

Thanks and best regards

Patrick

**Comment by mickenordin** [comment]
I don't seem to have gotten a notification about this... Sorry about that.

The second factor is one that is configured in settings->security. You need to enable a second factor provider such as totp or webauthn. I will see if I can make the documentation a bit more clear.

**Comment by mickenordin** [comment]
I added some more info here: a988b1ca5c03b0ced021393f7ea62ab92e16bb2e
