### ISSUE TITLE
Files in MFA Zones transferred to non-MFA users can be deleted and then individually restored to gain access to the files

### ISSUE THREAD

**Issue by sunetfreitag** [SUNET/nextcloud-mfazones#20]
A non-MFA user can access MFA protected files if they are received via transfer of ownership and then deleted.

**Steps to reproduce**
1. Log on with an MFA user account
2. Create a folder and activate the MFA zone
3. Create a file in the subfolder
4. Transfer the ownership of the folder via (user settings) --> Sharing to a non-MFA user account
5. Log on with the non-MFA user account
6. Accept the data transfer in the notification
7. Wait until the folder shows up or manually trigger cron.php
8. The folder shows up in the main folder under "transferred from <mfauser> on <timestamp>" and is labeled as an MFA Zone
9. The files cannot be accessed by the non-MFA user
10. Delete the transferred folder
11. Go to your deleted files
12. The files from the MFA Zone show up in the deleted files
13. Restore an individual file that previously resided in an MFA Zone
14. The folder is restored to the user's home folder and can be accessed/edited/modified regularly

A bit of an edge-case that involves a lot of user interaction. The question here probably is at which point the MFA Zone requirement of a folder should be enforced. This might also be more related to the workflow engine, i.e., what happens when a folder implementing a workflow is transferred to a user that does not meet the requirements of the configured workflow.

**Comment by mickenordin** [comment]
We enforce MFA zones on folder level, maybe we should look into setting MFA tags on all files in the folder too. I don't know if tags are preserved on deletion but the described procedure is an unexpected way to move a file from a folder.

**Comment by mickenordin** [comment]
This should be fixed in v0.2.0. We now set mfazone recursivly on all files and folders in an mfazone.
